;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        View-leave
        avy-goto-char
        coffee-dedent-line-backspace
        comment-or-uncomment-region
        complete-symbol
        downcase-region
        electric-newline-and-maybe-indent
        forward-sentence
        helm-ff-RET
        helm-keyboard-quit
        keyboard-escape-quit
        kill-region
        kill-ring-save
        markdown-outdent-or-delete
        org-end-of-line
        org-yank
        sgml-delete-tag
        sgml-slash
        sp-remove-active-pair-overlay
        tom/move-line-up
        upcase-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        abort-recursive-edit
        emmet-expand-line
        god-mode-all
        god-mode-self-insert
        helm-M-x
        helm-maybe-exit-minibuffer
        helm-swoop
        indent-for-tab-command
        mac-mouse-buffer-menu
        mac-mwheel-scroll
        mac-previous-tab-or-toggle-tab-bar
        mark-whole-buffer
        org-beginning-of-line
        org-return
        org-self-insert-command
        revert-buffer
        rjsx-electric-gt
        rjsx-electric-lt
        toggle-input-method
        wdired-finish-edit
        ))
