;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	View-leave
	avy-goto-char
	complete-symbol
	electric-newline-and-maybe-indent
	helm-ff-RET
	helm-keyboard-quit
	keyboard-escape-quit
	markdown-outdent-or-delete
	sgml-delete-tag
	sgml-slash
	sp-remove-active-pair-overlay
	tom/move-line-up
	))

(setq mc/cmds-to-run-once
      '(
	emmet-expand-line
	god-mode-all
	god-mode-self-insert
	helm-M-x
	helm-maybe-exit-minibuffer
	indent-for-tab-command
	mac-mwheel-scroll
	mark-whole-buffer
	org-return
	org-self-insert-command
	rjsx-electric-gt
	rjsx-electric-lt
	))
