;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	avy-goto-char
	complete-symbol
	keyboard-escape-quit
	sgml-delete-tag
	))

(setq mc/cmds-to-run-once
      '(
	god-mode-all
	god-mode-self-insert
	helm-maybe-exit-minibuffer
	indent-for-tab-command
	rjsx-electric-lt
	))
