;;; helm-rg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-rg.el

(autoload 'helm-rg "helm-rg" "\
Search for the perl regexp RG-PATTERN extremely quickly with ripgrep.

\\{helm-rg-map}

(fn RG-PATTERN &optional PFX)" t)
(register-definition-prefixes "helm-rg" '("helm-rg-"))

;;; End of scraped data

(provide 'helm-rg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-rg-autoloads.el ends here
